[package]
name = "collects-services"
version = "0.1.0"
authors = ["BoWen Chai <chaibowen.i@gmail.com>"]
edition = "2024"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[dependencies]
anyhow = { workspace = true}
axum = { workspace = true }
axum-extra = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true }
opendal = { workspace = true }
reqwest = { workspace = true, default-features = true }
serde = { workspace = true }
serde-env = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio  = { workspace = true, features = ["full"] }
tracing  = { workspace = true }
tracing-subscriber  = { workspace = true }
tracing-stackdriver = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
mimalloc = { workspace = true }

[dev-dependencies]
axum-test = "18.1.0"

[build-dependencies]
chrono = "0.4.42"
