[package]
name = "collects-services"
version = "0.1.0"
authors = ["BoWen Chai <chaibowen.i@gmail.com>"]
edition = "2024"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[dependencies]
anyhow = { workspace = true}
async-trait = "0.1"
axum = { workspace = true }
axum-extra = { version = "0.9.2", features = ["typed-header"] }

jsonwebtoken = "9.3.0"
opendal = { workspace = true }
reqwest = { version = "0.12.5", features = ["json"] }
serde.workspace = true
serde-env = "0.2.0"
serde_json.workspace = true
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio  = { workspace = true }
tracing  = { workspace = true }
tracing-subscriber  = { workspace = true }
mimalloc = { workspace = true }

[dev-dependencies]
axum-test = "18.1.0"

[build-dependencies]
chrono = "0.4.42"
