[package]
name = "collects-states"
version = "0.1.0"
authors = ["BoWen Chai <chaibowen.i@gmail.com>"]
edition = "2024"

[dependencies]
flume = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
bumpalo = { workspace = true }
thiserror = { workspace = true }
foyer = { workspace = true }
ustr = { workspace = true }
chrono = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }
