[package]
name = "collects-utils"
version = "0.1.0"
authors = ["BoWen Chai <chaibowen.i@gmail.com>"]
edition = "2024"
license = "MIT"

[build-dependencies]
chrono = "0.4.42"

[features]
env_test = []
env_test_internal = []
env_pr = []
env_internal = []
env_nightly = []
