[package]
name = "collects-ui"
version = "0.1.0"
authors = ["BoWen Chai <chaibowen.i@gmail.com>"]
edition = "2024"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
egui = { workspace = true }
eframe = { workspace = true }
ehttp = { workspace = true }
flume = { workspace = true }
chrono = { workspace = true }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
collects-business = { path = "../business" }
collects-states = { path = "../states" }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"
mimalloc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, default-features = true }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
kittest = "0.3"
wiremock = "0.6"
egui_kittest = "0.33"
tokio = { workspace = true, features = ["full", "test-util"] }

[features]
env_test = ["collects-business/env_test"]
env_internal = ["collects-business/env_internal"]
env_nightly = ["collects-business/env_nightly"]
