name = "collects-app-pr"
main = "src/worker.ts"
compatibility_date = "2025-09-15"

[[routes]]
pattern = "collects-pr.lqxclqxc.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [ "/api/*", "/wasm/*" ]

[[kv_namespaces]]
binding = "KV"
id = "fac40588d16f4fa8b7c8f36de6445649"

[[r2_buckets]]
binding = "WASM_BUCKET"
bucket_name = "collects-wasm"

[vars]
API_BASE = "https://collects-services-pr-145756646168.us-east1.run.app"

[observability]
enabled = true
