name = "collects-app-internal"
main = "src/worker.ts"
compatibility_date = "2025-09-15"

[[routes]]
pattern = "collects-internal.lqxclqxc.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[[kv_namespaces]]
binding = "KV"
id = "fac40588d16f4fa8b7c8f36de6445649"

[vars]
API_BASE = "https://collects-api-internal-145756646168.us-east1.run.app"
